use std::path::PathBuf;

use colored::Colorize;

use crate::{captain_home, daemon_client, find_daemon, ui};

pub(crate) fn cmd_integration_add(name: &str, key: Option<&str>) {
    let home = captain_home();
    let mut registry = captain_extensions::registry::IntegrationRegistry::new(&home);
    registry.load_bundled();
    let _ = registry.load_installed();

    let template = match registry.get_template(name) {
        Some(t) => t.clone(),
        None => {
            ui::error(&format!("Unknown integration: '{name}'"));
            println!("\nAvailable integrations:");
            for t in registry.list_templates() {
                println!("  {} {} — {}", t.icon, t.id, t.description);
            }
            std::process::exit(1);
        }
    };

    let secrets_path = home.join("secrets.env");
    let dotenv_path = home.join(".env");
    let vault_path = home.join("vault.enc");
    let vault = if vault_path.exists() {
        let mut v = captain_extensions::vault::CredentialVault::new(vault_path);
        if v.unlock().is_ok() {
            Some(v)
        } else {
            None
        }
    } else {
        None
    };
    let mut resolver = captain_extensions::credentials::CredentialResolver::new_with_secrets(
        vault,
        Some(&secrets_path),
        Some(&dotenv_path),
    )
    .with_interactive(true);

    let mut provided_keys = std::collections::HashMap::new();
    if let Some(key_value) = key {
        if let Some(env_var) = template.required_env.iter().find(|e| e.is_secret) {
            provided_keys.insert(env_var.name.clone(), key_value.to_string());
        }
    }

    match captain_extensions::installer::install_integration(
        &mut registry,
        &mut resolver,
        name,
        &provided_keys,
    ) {
        Ok(result) => {
            match &result.status {
                captain_extensions::IntegrationStatus::Ready => ui::success(&result.message),
                captain_extensions::IntegrationStatus::Setup => {
                    println!("{}", result.message.yellow());
                    println!("\nTo add credentials:");
                    for env in &template.required_env {
                        if env.is_secret {
                            println!("  captain vault set {}  # {}", env.name, env.help);
                            if let Some(ref url) = env.get_url {
                                println!("  Get it here: {url}");
                            }
                        }
                    }
                }
                _ => println!("{}", result.message),
            }
            request_integrations_reload();
        }
        Err(e) => {
            ui::error(&e.to_string());
            std::process::exit(1);
        }
    }
}

pub(crate) fn cmd_integration_remove(name: &str) {
    let home = captain_home();
    let mut registry = captain_extensions::registry::IntegrationRegistry::new(&home);
    registry.load_bundled();
    let _ = registry.load_installed();

    match captain_extensions::installer::remove_integration(&mut registry, name) {
        Ok(msg) => {
            ui::success(&msg);
            request_integrations_reload();
        }
        Err(e) => {
            ui::error(&e.to_string());
            std::process::exit(1);
        }
    }
}

pub(crate) fn cmd_integrations_doc(out: Option<PathBuf>) {
    let entries = list_registry_entries(None);
    let mut by_category = group_by_category(&entries);
    let mut md = String::new();
    md.push_str("# Captain — Integrations Reference\n\n");
    md.push_str(&format!(
        "> Auto-generated by `captain integrations --doc`. {} integration(s) registered.\n\n",
        entries.len()
    ));

    if entries.is_empty() {
        md.push_str("_No integrations available._\n");
    } else {
        for (category, items) in &mut by_category {
            md.push_str(&format!("## {category}\n\n"));
            md.push_str("| ID | Status | Description |\n|---|---|---|\n");
            for item in items {
                let status = match &item.status {
                    captain_extensions::IntegrationStatus::Ready => "ready",
                    captain_extensions::IntegrationStatus::Setup => "setup",
                    captain_extensions::IntegrationStatus::Available => "available",
                    captain_extensions::IntegrationStatus::Error(_) => "error",
                    captain_extensions::IntegrationStatus::Disabled => "disabled",
                };
                md.push_str(&format!(
                    "| `{}` | {} | {} |\n",
                    item.id,
                    status,
                    item.description.replace('|', "\\|"),
                ));
            }
            md.push('\n');
        }
    }

    match out {
        Some(path) => match std::fs::write(&path, &md) {
            Ok(()) => println!("Wrote {} ({} bytes)", path.display(), md.len()),
            Err(e) => {
                eprintln!("Failed to write {}: {e}", path.display());
                std::process::exit(1);
            }
        },
        None => print!("{md}"),
    }
}

pub(crate) fn cmd_integrations_list(query: Option<&str>) {
    let entries = list_registry_entries(query);
    if entries.is_empty() {
        if let Some(q) = query {
            println!("No integrations matching '{q}'.");
        } else {
            println!("No integrations available.");
        }
        return;
    }

    let mut by_category = group_by_category(&entries);
    for (category, items) in &mut by_category {
        println!("\n{}", format!("  {category}").bold());
        for item in items {
            let status_badge = match &item.status {
                captain_extensions::IntegrationStatus::Ready => "[Ready]".green().to_string(),
                captain_extensions::IntegrationStatus::Setup => "[Setup]".yellow().to_string(),
                captain_extensions::IntegrationStatus::Available => {
                    "[Available]".dimmed().to_string()
                }
                captain_extensions::IntegrationStatus::Error(msg) => {
                    format!("[Error: {msg}]").red().to_string()
                }
                captain_extensions::IntegrationStatus::Disabled => {
                    "[Disabled]".dimmed().to_string()
                }
            };
            println!(
                "    {} {:<20} {:<12} {}",
                item.icon, item.id, status_badge, item.description
            );
        }
    }
    println!();
    println!(
        "  {} integrations ({} installed)",
        entries.len(),
        entries
            .iter()
            .filter(|e| matches!(
                e.status,
                captain_extensions::IntegrationStatus::Ready
                    | captain_extensions::IntegrationStatus::Setup
            ))
            .count()
    );
    println!("  Use `captain add <name>` to install an integration.");
}

fn request_integrations_reload() {
    if let Some(base_url) = find_daemon() {
        let client = daemon_client();
        let _ = client
            .post(format!("{base_url}/api/integrations/reload"))
            .send();
    }
}

fn list_registry_entries(
    query: Option<&str>,
) -> Vec<captain_extensions::installer::IntegrationListEntry> {
    let home = captain_home();
    let mut registry = captain_extensions::registry::IntegrationRegistry::new(&home);
    registry.load_bundled();
    let _ = registry.load_installed();

    let secrets_path = home.join("secrets.env");
    let dotenv_path = home.join(".env");
    let resolver = captain_extensions::credentials::CredentialResolver::new_with_secrets(
        None,
        Some(&secrets_path),
        Some(&dotenv_path),
    );

    if let Some(q) = query {
        captain_extensions::installer::search_integrations(&registry, q)
    } else {
        captain_extensions::installer::list_integrations(&registry, &resolver)
    }
}

fn group_by_category(
    entries: &[captain_extensions::installer::IntegrationListEntry],
) -> std::collections::BTreeMap<String, Vec<&captain_extensions::installer::IntegrationListEntry>> {
    let mut by_category = std::collections::BTreeMap::new();
    for entry in entries {
        by_category
            .entry(entry.category.clone())
            .or_insert_with(Vec::new)
            .push(entry);
    }
    by_category
}
