pub(crate) mod agent;
mod agent_api;
mod agent_caps;
pub(crate) mod approvals;
pub(crate) mod auth;
mod auth_codex;
pub(crate) mod autonomy;
pub(crate) mod channel;
pub(crate) mod channel_inbound;
pub(crate) mod chat;
pub(crate) mod completion;
pub(crate) mod config;
mod config_secrets;
mod config_workspace;
pub(crate) mod cron;
pub(crate) mod daemon;
pub(crate) mod devices;
pub(crate) mod dispatch;
pub(crate) mod doctor;
pub(crate) mod embeddings;
pub(crate) mod hand;
pub(crate) mod health;
pub(crate) mod init;
pub(crate) mod integration;
pub(crate) mod integrations;
mod log_events;
pub(crate) mod logs;
pub(crate) mod memory;
pub(crate) mod message;
mod model_state;
pub(crate) mod models;
pub(crate) mod process;
pub(crate) mod project;
mod project_checkpoints;
mod project_context;
mod project_goals;
mod project_list;
mod project_milestones;
mod project_questions;
mod project_replay;
mod project_replay_render;
mod project_runtime_actions;
mod project_runtime_view;
mod project_tasks;
mod project_timeline;
mod project_worker_window;
mod project_workers;
mod replay;
pub(crate) mod scaffold;
pub(crate) mod security;
pub(crate) mod service;
mod service_render;
mod service_runtime;
mod session_api;
mod session_text;
pub(crate) mod sessions;
pub(crate) mod setup;
pub(crate) mod setup_access;
pub(crate) mod setup_docker;
pub(crate) mod setup_integrations;
mod setup_model;
pub(crate) mod setup_options;
pub(crate) mod setup_profile;
pub(crate) mod setup_support;
pub(crate) mod setup_surface;
pub(crate) mod skill;
pub(crate) mod ssh;
pub(crate) mod status;
mod status_compat;
mod status_health;
mod status_in_process;
mod status_project_attention;
mod status_project_attention_metadata;
mod status_project_attention_render;
mod status_project_attention_safe;
mod status_shutdown;
mod status_verbose;
mod status_workload;
pub(crate) mod system;
pub(crate) mod terminal;
pub(crate) mod trigger;
pub(crate) mod uninstall;
pub(crate) mod update;
pub(crate) mod vault;
pub(crate) mod voice;
pub(crate) mod voice_install;
pub(crate) mod webhooks;
pub(crate) mod workflow;

pub(crate) use session_api::require_agent_id;
