use captain_types::model_catalog::{ModelCatalogEntry, ModelTier};

struct OpenRouterModelRow {
    id: &'static str,
    display_name: &'static str,
    tier: ModelTier,
    context_window: u64,
    max_output_tokens: u64,
    input_cost_per_m: f64,
    output_cost_per_m: f64,
    supports_tools: bool,
    supports_vision: bool,
    aliases: &'static [&'static str],
}

fn openrouter_model(row: &OpenRouterModelRow) -> ModelCatalogEntry {
    ModelCatalogEntry {
        id: row.id.into(),
        display_name: row.display_name.into(),
        provider: "openrouter".into(),
        tier: row.tier,
        context_window: row.context_window,
        max_output_tokens: row.max_output_tokens,
        input_cost_per_m: row.input_cost_per_m,
        output_cost_per_m: row.output_cost_per_m,
        supports_tools: row.supports_tools,
        supports_vision: row.supports_vision,
        supports_streaming: true,
        aliases: row.aliases.iter().map(|alias| (*alias).into()).collect(),
    }
}

fn openrouter_models(rows: &[OpenRouterModelRow]) -> Vec<ModelCatalogEntry> {
    rows.iter().map(openrouter_model).collect()
}

const OPENROUTER_MODELS_BEFORE_MISTRAL: &[OpenRouterModelRow] = &[
    OpenRouterModelRow {
        id: "openrouter/google/gemini-2.5-flash",
        display_name: "Gemini 2.5 Flash (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 1_048_576,
        max_output_tokens: 65_536,
        input_cost_per_m: 0.15,
        output_cost_per_m: 0.60,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/anthropic/claude-sonnet-4",
        display_name: "Claude Sonnet 4 (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 200_000,
        max_output_tokens: 64_000,
        input_cost_per_m: 3.0,
        output_cost_per_m: 15.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/openai/gpt-4o",
        display_name: "GPT-4o (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 128_000,
        max_output_tokens: 16_384,
        input_cost_per_m: 2.5,
        output_cost_per_m: 10.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/deepseek/deepseek-chat",
        display_name: "DeepSeek V3 (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.14,
        output_cost_per_m: 0.28,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/meta-llama/llama-3.3-70b-instruct",
        display_name: "Llama 3.3 70B (OpenRouter)",
        tier: ModelTier::Balanced,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.39,
        output_cost_per_m: 0.39,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/qwen/qwen-2.5-72b-instruct",
        display_name: "Qwen 2.5 72B (OpenRouter)",
        tier: ModelTier::Balanced,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.36,
        output_cost_per_m: 0.36,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/google/gemini-2.5-pro",
        display_name: "Gemini 2.5 Pro (OpenRouter)",
        tier: ModelTier::Frontier,
        context_window: 1_048_576,
        max_output_tokens: 65_536,
        input_cost_per_m: 1.25,
        output_cost_per_m: 10.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/mistralai/mistral-large-latest",
        display_name: "Mistral Large (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 128_000,
        max_output_tokens: 8_192,
        input_cost_per_m: 2.0,
        output_cost_per_m: 6.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/google/gemma-2-9b-it",
        display_name: "Gemma 2 9B (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 8_192,
        max_output_tokens: 4_096,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/deepseek/deepseek-r1",
        display_name: "DeepSeek R1 (OpenRouter)",
        tier: ModelTier::Frontier,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.55,
        output_cost_per_m: 2.19,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/google/gemma-2-9b-it:free",
        display_name: "Gemma 2 9B Free (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 8_192,
        max_output_tokens: 4_096,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/meta-llama/llama-3.1-8b-instruct:free",
        display_name: "Llama 3.1 8B Free (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 131_072,
        max_output_tokens: 4_096,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/qwen/qwen-2.5-7b-instruct:free",
        display_name: "Qwen 2.5 7B Free (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 32_768,
        max_output_tokens: 4_096,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/mistralai/mistral-7b-instruct:free",
        display_name: "Mistral 7B Free (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 32_768,
        max_output_tokens: 4_096,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/huggingfaceh4/zephyr-7b-beta:free",
        display_name: "Zephyr 7B Free (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 4_096,
        max_output_tokens: 2_048,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/deepseek/deepseek-r1:free",
        display_name: "DeepSeek R1 Free (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: false,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/hunter-alpha",
        display_name: "Hunter Alpha (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 131_072,
        max_output_tokens: 8_192,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &["hunter-alpha"],
    },
    OpenRouterModelRow {
        id: "openrouter/qwen/qwen3-235b-a22b-instruct",
        display_name: "Qwen3 235B Instruct (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 131_072,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.20,
        output_cost_per_m: 0.60,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/qwen/qwen3-30b-a3b-instruct",
        display_name: "Qwen3 30B Instruct (OpenRouter)",
        tier: ModelTier::Balanced,
        context_window: 131_072,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.10,
        output_cost_per_m: 0.30,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/anthropic/claude-haiku-4.5",
        display_name: "Claude Haiku 4.5 (OpenRouter)",
        tier: ModelTier::Balanced,
        context_window: 200_000,
        max_output_tokens: 8_192,
        input_cost_per_m: 1.0,
        output_cost_per_m: 5.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/anthropic/claude-sonnet-4.6",
        display_name: "Claude Sonnet 4.6 (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 200_000,
        max_output_tokens: 64_000,
        input_cost_per_m: 3.0,
        output_cost_per_m: 15.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/google/gemini-2.5-flash",
        display_name: "Gemini 2.5 Flash (OpenRouter)",
        tier: ModelTier::Fast,
        context_window: 1_048_576,
        max_output_tokens: 8_192,
        input_cost_per_m: 0.075,
        output_cost_per_m: 0.30,
        supports_tools: true,
        supports_vision: true,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/deepseek/deepseek-v3.1",
        display_name: "DeepSeek V3.1 (OpenRouter)",
        tier: ModelTier::Smart,
        context_window: 128_000,
        max_output_tokens: 32_768,
        input_cost_per_m: 0.27,
        output_cost_per_m: 1.10,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
    OpenRouterModelRow {
        id: "openrouter/x-ai/grok-4-fast",
        display_name: "Grok 4 Fast (OpenRouter)",
        tier: ModelTier::Balanced,
        context_window: 256_000,
        max_output_tokens: 8_192,
        input_cost_per_m: 0.20,
        output_cost_per_m: 0.50,
        supports_tools: true,
        supports_vision: false,
        aliases: &[],
    },
];

const OPENROUTER_MODELS_AFTER_MISTRAL: &[OpenRouterModelRow] = &[
    OpenRouterModelRow {
        id: "xiaomi/mimo-v2-flash",
        display_name: "MiMo v2 Flash",
        tier: ModelTier::Fast,
        context_window: 262_144,
        max_output_tokens: 8_192,
        input_cost_per_m: 0.09,
        output_cost_per_m: 0.29,
        supports_tools: true,
        supports_vision: false,
        aliases: &["mimo-flash"],
    },
    OpenRouterModelRow {
        id: "xiaomi/mimo-v2-omni",
        display_name: "MiMo v2 Omni",
        tier: ModelTier::Balanced,
        context_window: 262_144,
        max_output_tokens: 8_192,
        input_cost_per_m: 0.40,
        output_cost_per_m: 2.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &["mimo-omni"],
    },
    OpenRouterModelRow {
        id: "xiaomi/mimo-v2-pro",
        display_name: "MiMo v2 Pro",
        tier: ModelTier::Smart,
        context_window: 1_048_576,
        max_output_tokens: 8_192,
        input_cost_per_m: 1.0,
        output_cost_per_m: 3.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &["mimo-pro", "mimo"],
    },
    OpenRouterModelRow {
        id: "xiaomi/mimo-v2.5-pro",
        display_name: "MiMo v2.5 Pro",
        tier: ModelTier::Smart,
        context_window: 1_048_576,
        max_output_tokens: 8_192,
        input_cost_per_m: 1.0,
        output_cost_per_m: 3.0,
        supports_tools: true,
        supports_vision: false,
        aliases: &["mimo-2.5-pro", "mimo2.5"],
    },
    OpenRouterModelRow {
        id: "deepseek/deepseek-v4-pro",
        display_name: "DeepSeek V4 Pro",
        tier: ModelTier::Frontier,
        context_window: 1_048_576,
        max_output_tokens: 384_000,
        input_cost_per_m: 0.435,
        output_cost_per_m: 0.87,
        supports_tools: true,
        supports_vision: false,
        aliases: &["deepseek-v4-pro", "deepseek-v4"],
    },
    OpenRouterModelRow {
        id: "moonshotai/kimi-k2-0905",
        display_name: "Kimi K2 0905",
        tier: ModelTier::Frontier,
        context_window: 262_144,
        max_output_tokens: 16_384,
        input_cost_per_m: 0.40,
        output_cost_per_m: 2.00,
        supports_tools: true,
        supports_vision: false,
        aliases: &["kimi-k2-openrouter"],
    },
    OpenRouterModelRow {
        id: "moonshotai/kimi-k2.6",
        display_name: "Kimi K2.6",
        tier: ModelTier::Frontier,
        context_window: 256_000,
        max_output_tokens: 16_384,
        input_cost_per_m: 0.7448,
        output_cost_per_m: 4.655,
        supports_tools: true,
        supports_vision: true,
        aliases: &["kimi-k2.6-openrouter"],
    },
    OpenRouterModelRow {
        id: "qwen/qwen3.6-plus:free",
        display_name: "Qwen 3.6 Plus (Free)",
        tier: ModelTier::Smart,
        context_window: 1_000_000,
        max_output_tokens: 65_536,
        input_cost_per_m: 0.0,
        output_cost_per_m: 0.0,
        supports_tools: true,
        supports_vision: true,
        aliases: &["qwen3.6-plus"],
    },
];

pub(crate) fn openrouter_models_before_mistral() -> Vec<ModelCatalogEntry> {
    openrouter_models(OPENROUTER_MODELS_BEFORE_MISTRAL)
}

pub(crate) fn openrouter_models_after_mistral() -> Vec<ModelCatalogEntry> {
    openrouter_models(OPENROUTER_MODELS_AFTER_MISTRAL)
}
