//! Auto-summarize inactive sessions into structured checkpoint.md files.
//!
//! Each persisted session under `~/.captain/sessions/<agent>/*.json` is
//! the raw transcript — replaying it costs tokens and rarely answers
//! "what did we conclude on X two days ago?". This module's job is to
//! distill each inactive session into a short, predictable markdown
//! file (`<session>.checkpoint.md`) that lives next to the JSON and
//! can be grepped or fed back to the LLM cheaply.
//!
//! The summary is generated by a configured `ReflectionCompleter` so we
//! stay on the same production path as the rest of the learning pipeline.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};

use crate::learning_bus::{self, LearningSignal};
use crate::reflection_job::ReflectionCompleter;
use crate::session_summarizer_recall::sessions_root_for_json;
pub use crate::session_summarizer_recall::{
    index_checkpoint, matches_query, recall_checkpoints, session_index_path, RecallHit,
};

/// Runtime settings for the background session checkpoint summarizer.
#[derive(Debug, Clone)]
pub struct SessionSummarizerConfig {
    pub inactivity_secs: u64,
    pub scan_interval_secs: u64,
    pub per_summary_delay_secs: u64,
    pub transcript_cap_chars: usize,
    pub emit_learning_review: bool,
}

impl Default for SessionSummarizerConfig {
    fn default() -> Self {
        Self {
            inactivity_secs: DEFAULT_INACTIVITY_SECS,
            scan_interval_secs: SCAN_INTERVAL_SECS,
            per_summary_delay_secs: PER_SUMMARY_DELAY_SECS,
            transcript_cap_chars: TRANSCRIPT_CAP_CHARS,
            emit_learning_review: true,
        }
    }
}

/// Minimal projection of the TUI's PersistedSession that this module
/// needs. Defined here (rather than reusing `captain-cli`) to avoid a
/// crate-level cyclic dep — the summarizer must run inside the kernel
/// crate which sits *below* the CLI.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PersistedTurn {
    pub role: String,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct LoadedSession {
    pub agent_name: String,
    #[serde(default)]
    pub messages: Vec<PersistedTurn>,
    #[serde(default)]
    pub created_at: u64,
    #[serde(default)]
    pub updated_at: u64,
}

/// Render the markdown front matter that every checkpoint shares.
pub fn checkpoint_frontmatter(
    session_id: &str,
    agent_key: &str,
    updated_at: u64,
    message_count: usize,
    summarized_at_mtime: u64,
) -> String {
    format!(
        "---\nsession_id: {session_id}\nagent_key: {agent_key}\nupdated_at: {updated_at}\nmessage_count: {message_count}\nsummarized_at_mtime: {summarized_at_mtime}\n---\n"
    )
}

/// Build the system prompt fed to Haiku. Short, deterministic, asks
/// for exactly the 5 sections we want — anything else is a parse risk.
pub fn summarizer_system_prompt() -> &'static str {
    "Tu es un assistant qui résume des sessions de chat entre un développeur \
    et un agent IA. Produit un markdown court et structuré avec EXACTEMENT \
    ces 5 sections (titres en français, tels quels) :\n\
    \n\
    # Sujets\n\
    # Décisions\n\
    # Erreurs / Échecs\n\
    # Réussites\n\
    # Infos durables\n\
    \n\
    Pour chaque section, écris des bullets courts (5-12 mots). N'invente \
    rien — si une section est vide, écris une seule ligne `- (rien)`. \
    Ne mets aucun autre titre, aucune intro, aucune conclusion."
}

/// Build the user message for the summarizer: the session transcript
/// flattened in role: text form, capped to keep the prompt small.
pub fn build_summarizer_user_prompt(session: &LoadedSession, max_chars: usize) -> String {
    let mut buf = String::new();
    let mut written = 0usize;
    for turn in &session.messages {
        let line = format!("{}: {}\n", turn.role, turn.text.trim());
        if written + line.len() > max_chars {
            buf.push_str("...\n[transcript truncated]\n");
            break;
        }
        written += line.len();
        buf.push_str(&line);
    }
    buf
}

/// Decide whether we should (re-)summarize a session. The job re-runs
/// when the JSON has been modified after the checkpoint was written.
/// Returns `false` when:
/// - the session is empty / too short to be worth summarizing
/// - a checkpoint already exists and its `summarized_at_mtime` is
///   greater or equal to the JSON's mtime
pub fn should_summarize(
    session: &LoadedSession,
    json_mtime: u64,
    existing_checkpoint_mtime: Option<u64>,
) -> bool {
    if session.messages.len() < 3 {
        return false;
    }
    match existing_checkpoint_mtime {
        Some(prev) => json_mtime > prev,
        None => true,
    }
}

/// Where the checkpoint lives next to the JSON.
pub fn checkpoint_path_for(json_path: &Path) -> PathBuf {
    let stem = json_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("session");
    let parent = json_path.parent().unwrap_or(Path::new("."));
    parent.join(format!("{stem}.checkpoint.md"))
}

/// Read the `summarized_at_mtime: NNN` line from an existing checkpoint
/// markdown front matter. Returns `None` if the file is missing or the
/// field can't be parsed — the caller treats that as "needs summary".
pub fn read_checkpoint_mtime(checkpoint_path: &Path) -> Option<u64> {
    let raw = std::fs::read_to_string(checkpoint_path).ok()?;
    for line in raw.lines() {
        if let Some(rest) = line.strip_prefix("summarized_at_mtime:") {
            return rest.trim().parse().ok();
        }
    }
    None
}

/// Compose the final checkpoint markdown: frontmatter + body produced
/// by Haiku. The body is trusted as-is (Haiku is constrained by the
/// system prompt to emit our 5 sections).
pub fn assemble_checkpoint(
    session_id: &str,
    agent_key: &str,
    session: &LoadedSession,
    summarized_at_mtime: u64,
    summary_body: &str,
) -> String {
    let mut out = checkpoint_frontmatter(
        session_id,
        agent_key,
        session.updated_at,
        session.messages.len(),
        summarized_at_mtime,
    );
    out.push('\n');
    out.push_str(summary_body.trim());
    out.push('\n');
    out
}

/// Build the staged learning review emitted after an idle-session
/// checkpoint. The checkpoint captures what happened; this review tells
/// the learning pipeline how to reason about it without creating
/// duplicate memories.
pub fn build_learning_stage_review(
    session_id: &str,
    agent_key: &str,
    summary_body: &str,
) -> String {
    format!(
        "OBSERVE → Session `{session_id}` for agent `{agent_key}` became inactive and was summarized.\n\
        THINK → Identify durable facts, recurring workflow patterns, validated tool routes, and failed assumptions.\n\
        PLAN → Keep only memories or skill improvements that will help future sessions; skip one-off details.\n\
        BUILD → Convert candidates into concise triples or reusable skill-improvement notes.\n\
        EXECUTE → Send candidates through policy, secret scanning, approval mode, and configured autonomy limits.\n\
        VERIFY → Compare subject/predicate/object against existing learnings and reject duplicates or near-duplicates.\n\
        LEARN → Store only non-duplicate, durable learnings that Captain should still know later.\n\n\
        CHECKPOINT:\n{summary_body}"
    )
}

/// Inactivity threshold — JSON files older than this many seconds are
/// candidates for summarization. The user validated 10 minutes.
pub const DEFAULT_INACTIVITY_SECS: u64 = 600;

/// How often the background scanner wakes up to look for inactive sessions.
pub const SCAN_INTERVAL_SECS: u64 = 300;

/// Throttle between two summarizations within the same scan pass — keeps
/// us under any provider rate limit on the boot pass that finds many
/// stale sessions at once.
const PER_SUMMARY_DELAY_SECS: u64 = 10;

/// Cap the transcript length we feed to the summarizer. Larger sessions get
/// truncated (the system prompt instructs the model to deal with the
/// truncation marker).
const TRANSCRIPT_CAP_CHARS: usize = 8_000;

/// Spawn the background task that scans `sessions_root` every few
/// minutes and summarizes any inactive session whose checkpoint is
/// missing or stale. Fire-and-forget; errors log at warn but never
/// panic. Returns the JoinHandle so the kernel can keep it for
/// shutdown bookkeeping.
pub fn spawn_session_summarizer_task(
    completer: Arc<dyn ReflectionCompleter>,
    sessions_root: PathBuf,
    model: String,
    config: SessionSummarizerConfig,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        info!(
            sessions_root = %sessions_root.display(),
            interval_secs = config.scan_interval_secs,
            inactivity_secs = config.inactivity_secs,
            transcript_cap_chars = config.transcript_cap_chars,
            "session summarizer task started"
        );
        let mut ticker =
            tokio::time::interval(Duration::from_secs(config.scan_interval_secs.max(1)));
        loop {
            ticker.tick().await;
            scan_and_summarize_once_with_config(
                completer.as_ref(),
                &sessions_root,
                &model,
                &config,
            )
            .await;
        }
    })
}

/// Single pass: walk `sessions_root` and summarize anything stale.
/// Public for tests + lazy fallback (commit 3 will call this on demand
/// when `session_recall` finds a hit but the checkpoint is missing).
pub async fn scan_and_summarize_once(
    completer: &dyn ReflectionCompleter,
    sessions_root: &Path,
    model: &str,
) {
    scan_and_summarize_once_with_config(
        completer,
        sessions_root,
        model,
        &SessionSummarizerConfig::default(),
    )
    .await;
}

pub async fn scan_and_summarize_once_with_config(
    completer: &dyn ReflectionCompleter,
    sessions_root: &Path,
    model: &str,
    config: &SessionSummarizerConfig,
) {
    let now = now_unix_secs();
    let agent_dirs = match std::fs::read_dir(sessions_root) {
        Ok(d) => d,
        Err(e) => {
            debug!(error = %e, root = %sessions_root.display(), "no sessions dir yet");
            return;
        }
    };
    for ad in agent_dirs.flatten() {
        if !ad.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let agent_key = ad.file_name().to_string_lossy().into_owned();
        let files = match std::fs::read_dir(ad.path()) {
            Ok(f) => f,
            Err(_) => continue,
        };
        for f in files.flatten() {
            let path = f.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            if !summarize_one_if_stale(completer, &path, &agent_key, now, model, config).await {
                continue;
            }
            if config.per_summary_delay_secs > 0 {
                tokio::time::sleep(Duration::from_secs(config.per_summary_delay_secs)).await;
            }
        }
    }
}

/// Inspect one JSON file and summarize it if it qualifies. Returns
/// `true` when a summary was actually written (so the caller can
/// throttle), `false` when skipped for any reason.
async fn summarize_one_if_stale(
    completer: &dyn ReflectionCompleter,
    json_path: &Path,
    agent_key: &str,
    now: u64,
    model: &str,
    config: &SessionSummarizerConfig,
) -> bool {
    let json_mtime = match json_path.metadata().and_then(|m| m.modified()) {
        Ok(m) => m
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0),
        Err(_) => return false,
    };
    if now.saturating_sub(json_mtime) < config.inactivity_secs {
        return false;
    }
    let raw = match std::fs::read_to_string(json_path) {
        Ok(r) => r,
        Err(_) => return false,
    };
    let session: LoadedSession = match serde_json::from_str(&raw) {
        Ok(s) => s,
        Err(_) => return false,
    };
    let checkpoint_path = checkpoint_path_for(json_path);
    let existing = read_checkpoint_mtime(&checkpoint_path);
    if !should_summarize(&session, json_mtime, existing) {
        return false;
    }
    let user_prompt = build_summarizer_user_prompt(&session, config.transcript_cap_chars.max(512));
    let body = match completer
        .complete(model, summarizer_system_prompt(), &user_prompt)
        .await
    {
        Ok(b) => b,
        Err(e) => {
            warn!(error = %e, path = %json_path.display(), "session summarize: completer failed");
            return false;
        }
    };
    let session_id = json_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("?")
        .to_string();
    let content = assemble_checkpoint(&session_id, agent_key, &session, json_mtime, &body);
    if let Err(e) = captain_types::durable_fs::atomic_write(&checkpoint_path, content.as_bytes()) {
        warn!(error = %e, path = %checkpoint_path.display(), "session summarize: write failed");
        return false;
    }
    if let Some(root) = sessions_root_for_json(json_path) {
        if let Err(e) = index_checkpoint(&root, &session_id, agent_key, session.updated_at, &body) {
            debug!(
                error = %e,
                path = %checkpoint_path.display(),
                "session checkpoint FTS index update failed"
            );
        }
    }
    info!(
        path = %checkpoint_path.display(),
        message_count = session.messages.len(),
        "session checkpoint written"
    );
    if config.emit_learning_review {
        let review = build_learning_stage_review(&session_id, agent_key, &body);
        match learning_bus::emit(LearningSignal::SessionLearningReview {
            agent_id: agent_key.to_string(),
            session_id,
            review,
            source: "session_summarizer.inactivity".to_string(),
        }) {
            learning_bus::EmitResult::Emitted => {
                debug!(path = %checkpoint_path.display(), "session learning review emitted");
            }
            other => {
                debug!(?other, path = %checkpoint_path.display(), "session learning review skipped");
            }
        }
    }
    true
}

/// Quick wallclock helper that swallows the rare SystemTimeError; the
/// summarizer is best-effort, never panics.
pub fn now_unix_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}
