//! Default config.toml rendering (v3.14-config.a).
//!
//! Produces a complete TOML document from `KernelConfig::default()`
//! so users and agents can see every configurable field at a glance.
//! The CLI (`captain config init`) and the boot reconciler
//! (v3.14-config.b) both call into here.
//!
//! Note: `Option::None` fields are omitted by `toml::ser` — the
//! header comment documents how to introspect optional keys.

#[cfg(test)]
use crate::config::find_direct_secret_assignments;
use crate::config::KernelConfig;

/// Header prepended by `render_default_toml_with_header`. Explains
/// the "everything visible, defaults shown" convention so the file
/// is self-describing.
pub const CONFIG_HEADER: &str = "\
# Captain configuration — every configurable field at its default value.
# ------------------------------------------------------------------
# Generated by `captain config init`. Safe to edit by hand.
#
# Secrets: never commit real keys here. Codex uses OAuth and keeps
# `api_key_env` empty; API providers should point `api_key_env` to an
# environment variable (ANTHROPIC_API_KEY, OPENROUTER_API_KEY, ...).
#
# Optional fields (Rust `Option<T>`) are omitted until set — see
# `docs/configuration.md` and `captain.toml.example` for optional keys.
#
# Reconciliation: `captain` will auto-append missing top-level keys
# on boot with a `# auto-added` comment so upgrades never need a
# manual rewrite. Your edits are preserved.
";

/// Serialize `KernelConfig::default()` to a pretty TOML string.
/// The returned TOML is valid input to `toml::from_str`.
pub fn render_default_toml() -> Result<String, toml::ser::Error> {
    toml::to_string_pretty(&KernelConfig::default())
}

/// Same as `render_default_toml` but prefixed with `CONFIG_HEADER`.
/// Use this for `captain config init`.
pub fn render_default_toml_with_header() -> Result<String, toml::ser::Error> {
    Ok(format!("{}\n{}", CONFIG_HEADER, render_default_toml()?))
}

/// List top-level TOML keys present in the default template but
/// missing from the user's config. Returns keys in the order they
/// appear in the default template so `reconcile` can append them in
/// a stable order.
///
/// "Top-level" means first-level tables and bare keys; nested tables
/// (`[tts.openai]`) are not split from their parent.
pub fn scan_missing_top_level_keys(user_toml: &str) -> Result<Vec<String>, ReconcileError> {
    let template = render_default_toml().map_err(ReconcileError::Render)?;
    let template_doc: toml_edit::DocumentMut = template
        .parse()
        .map_err(|e: toml_edit::TomlError| ReconcileError::Parse(e.to_string()))?;
    let user_doc: toml_edit::DocumentMut = user_toml
        .parse()
        .map_err(|e: toml_edit::TomlError| ReconcileError::Parse(e.to_string()))?;

    let user_top: std::collections::HashSet<String> = user_doc
        .as_table()
        .iter()
        .map(|(k, _)| k.to_string())
        .collect();

    let mut missing = Vec::new();
    for (key, _) in template_doc.as_table().iter() {
        if !user_top.contains(key) {
            missing.push(key.to_string());
        }
    }
    Ok(missing)
}

/// Reconcile a user config file against the default template:
/// append every missing top-level key/table with a
/// `# auto-added by captain v<version>` comment, preserving all
/// existing edits and comments in between.
///
/// Returns the list of keys that were added. An empty vec means the
/// file was already complete. If the file is malformed, returns an
/// error and does not touch it.
pub fn reconcile_file(
    path: &std::path::Path,
    version: &str,
) -> Result<Vec<String>, ReconcileError> {
    let content = std::fs::read_to_string(path).map_err(ReconcileError::Io)?;
    let added = reconcile_string(&content, version)?;
    if added.added_keys.is_empty() {
        return Ok(Vec::new());
    }
    std::fs::write(path, &added.reconciled).map_err(ReconcileError::Io)?;
    Ok(added.added_keys)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReconcileResult {
    pub reconciled: String,
    pub added_keys: Vec<String>,
}

/// In-memory reconcile. Separated from `reconcile_file` so the CLI
/// dry-run path and tests can exercise it without touching disk.
pub fn reconcile_string(user_toml: &str, version: &str) -> Result<ReconcileResult, ReconcileError> {
    let template = render_default_toml().map_err(ReconcileError::Render)?;
    let template_doc: toml_edit::DocumentMut = template
        .parse()
        .map_err(|e: toml_edit::TomlError| ReconcileError::Parse(e.to_string()))?;
    let mut user_doc: toml_edit::DocumentMut = user_toml
        .parse()
        .map_err(|e: toml_edit::TomlError| ReconcileError::Parse(e.to_string()))?;

    let mut added_keys = Vec::new();
    let user_top: std::collections::HashSet<String> = user_doc
        .as_table()
        .iter()
        .map(|(k, _)| k.to_string())
        .collect();

    for (key, item) in template_doc.as_table().iter() {
        if user_top.contains(key) {
            continue;
        }
        let mut cloned = item.clone();
        if let Some(tbl) = cloned.as_table_mut() {
            let decor = tbl.decor_mut();
            decor.set_prefix(format!("\n# auto-added by captain {version}\n"));
        } else {
            // Leaf value: attach the comment to the key via the
            // surrounding key decor. toml_edit's key-decor API
            // requires accessing the key through the table iterator,
            // so we just prepend a standalone comment line in the
            // output by inserting via the parent table path.
        }
        user_doc.insert(key, cloned);
        added_keys.push(key.to_string());
    }

    Ok(ReconcileResult {
        reconciled: user_doc.to_string(),
        added_keys,
    })
}

#[derive(Debug, thiserror::Error)]
pub enum ReconcileError {
    #[error("render default template: {0}")]
    Render(#[from] toml::ser::Error),
    #[error("parse TOML: {0}")]
    Parse(String),
    #[error(transparent)]
    Io(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_produces_non_empty_toml() {
        let s = render_default_toml().expect("render must succeed");
        assert!(s.len() > 100, "template should be substantial");
    }

    #[test]
    fn render_contains_core_sections() {
        let s = render_default_toml().expect("render");
        for section in [
            "[default_model]",
            "[agent_loop]",
            "[memory]",
            "[learning]",
            "[checkpoints]",
            "[skills]",
            "[channels]",
            "[browser]",
            "[web_terminal]",
            "[deployment]",
            "[voice_call]",
            "[auth]",
        ] {
            assert!(s.contains(section), "missing section {section}");
        }
    }

    #[test]
    fn render_exposes_v312_and_v313_fields() {
        let s = render_default_toml().expect("render");
        // v3.12 LearningEngine surface
        assert!(s.contains("reflection_model"));
        assert!(s.contains("fallback_models"));
        assert!(s.contains("min_confidence"));
        // v3.13 SkillSynthesizer surface
        assert!(s.contains("proposer_model"));
        assert!(s.contains("pattern_threshold"));
        assert!(s.contains("generated_dir"));
    }

    #[test]
    fn render_is_valid_toml_and_roundtrips_to_kernel_config() {
        let s = render_default_toml().expect("render");
        let parsed: KernelConfig =
            toml::from_str(&s).expect("rendered template must be valid TOML for KernelConfig");
        // A couple of spot checks — we don't PartialEq the whole struct
        // because it contains non-Eq types (HashMap, PathBuf) that
        // survive the round-trip but don't implement Eq.
        assert_eq!(parsed.default_model.provider, "codex");
        assert_eq!(parsed.default_model.model, "gpt-5.5");
        assert_eq!(parsed.default_model.api_key_env, "");
        assert!(parsed.surfaces.is_active(crate::config::ActiveSurface::Cli));
        assert!(parsed.surfaces.is_active(crate::config::ActiveSurface::Web));
        assert!(parsed
            .surfaces
            .is_active(crate::config::ActiveSurface::Telegram));
        assert!(parsed.surfaces.is_frozen_name("hands"));
        assert_eq!(parsed.agent_loop.max_iterations, 90);
        assert!(parsed.learning.enabled);
        assert!(parsed.checkpoints.enabled);
        assert_eq!(parsed.checkpoints.model, "gpt-5.5");
        assert!(parsed.skills.enabled);
        assert_eq!(parsed.learning.reflection_model, "gpt-5.5");
        assert!(parsed.learning.fallback_models.is_empty());
        assert_eq!(parsed.skills.proposer_model, "gpt-5.5");
        assert!(parsed.skills.fallback_models.is_empty());
        assert_eq!(parsed.skills.pattern_threshold, 5);
        assert_eq!(parsed.tts.local_native.preferred_engine, "kokoro");
        assert_eq!(parsed.tts.local_native.fallback_engine, "piper");
        assert!(parsed.media.audio_model.is_none());
        assert!(parsed.voice_call.enabled);
        assert_eq!(parsed.voice_call.model, "gpt-realtime-2");
        assert_eq!(parsed.voice_call.auto_end_silence_secs, 90);
        assert_eq!(parsed.voice_call.auto_end_inactive_secs, 180);
    }

    #[test]
    fn public_example_is_valid_toml_and_codex_first() {
        let raw = include_str!("../../../captain.toml.example");
        let parsed: KernelConfig =
            toml::from_str(raw).expect("captain.toml.example must parse as KernelConfig");

        assert_eq!(parsed.default_model.provider, "codex");
        assert_eq!(parsed.default_model.model, "gpt-5.5");
        assert_eq!(parsed.default_model.api_key_env, "");
        assert_eq!(parsed.learning.reflection_model, "gpt-5.5");
        assert!(parsed.learning.fallback_models.is_empty());
        assert_eq!(parsed.skills.proposer_model, "gpt-5.5");
        assert!(parsed.skills.fallback_models.is_empty());
        assert!(parsed.checkpoints.enabled);
        assert_eq!(parsed.checkpoints.model, "gpt-5.5");
    }

    #[test]
    fn render_with_header_starts_with_banner() {
        let s = render_default_toml_with_header().expect("render");
        assert!(s.starts_with("# Captain configuration"));
        assert!(s.contains("[default_model]"));
    }

    #[test]
    fn render_never_embeds_direct_secret_assignments() {
        let s = render_default_toml().expect("render");
        let leaks =
            find_direct_secret_assignments(&s).expect("rendered template must parse as TOML");
        assert!(
            leaks.is_empty(),
            "direct secrets leaked into template: {leaks:?}"
        );
    }

    #[test]
    fn public_example_never_embeds_direct_secret_assignments() {
        let raw = include_str!("../../../captain.toml.example");
        let leaks = find_direct_secret_assignments(raw).expect("public example must parse as TOML");
        assert!(
            leaks.is_empty(),
            "direct secrets leaked into public example: {leaks:?}"
        );
    }

    #[test]
    fn render_is_deterministic_across_calls() {
        let a = render_default_toml().expect("render a");
        let b = render_default_toml().expect("render b");
        assert_eq!(a, b, "render must be pure");
    }

    #[test]
    fn header_constant_mentions_captain_config_init() {
        assert!(CONFIG_HEADER.contains("captain config init"));
    }

    // ---- reconcile helpers ----

    #[test]
    fn scan_missing_detects_missing_sections() {
        let user = r#"
stt_model = "whisper-small"

[default_model]
provider = "openrouter"
model = "anthropic/claude-sonnet-4.6"
api_key_env = "OPENROUTER_API_KEY"
        "#;
        let missing = scan_missing_top_level_keys(user).unwrap();
        assert!(missing.contains(&"learning".to_string()));
        assert!(missing.contains(&"skills".to_string()));
        assert!(missing.contains(&"budget".to_string()));
        assert!(!missing.contains(&"default_model".to_string()));
    }

    #[test]
    fn scan_missing_empty_when_user_config_has_all_sections() {
        let full = render_default_toml().unwrap();
        let missing = scan_missing_top_level_keys(&full).unwrap();
        assert!(
            missing.is_empty(),
            "full template should have no missing keys: {missing:?}"
        );
    }

    #[test]
    fn scan_missing_parse_error_returned() {
        let bad = "not = valid [toml";
        let err = scan_missing_top_level_keys(bad).unwrap_err();
        assert!(matches!(err, ReconcileError::Parse(_)));
    }

    #[test]
    fn reconcile_preserves_user_edits_and_comments() {
        let user = r#"
# My personal config, keep my comments
stt_model = "whisper-small"

[default_model]
# I use OpenRouter
provider = "openrouter"
model = "anthropic/claude-sonnet-4.6"
api_key_env = "OPENROUTER_API_KEY"
"#;
        let r = reconcile_string(user, "v3.14").unwrap();
        assert!(!r.added_keys.is_empty());
        // User's custom comment survives.
        assert!(r
            .reconciled
            .contains("# My personal config, keep my comments"));
        assert!(r.reconciled.contains("# I use OpenRouter"));
        // Overridden value is preserved.
        assert!(r.reconciled.contains("provider = \"openrouter\""));
        assert!(!r.reconciled.contains("provider = \"codex\""));
        // Missing section appears.
        assert!(r.reconciled.contains("[learning]"));
    }

    #[test]
    fn reconcile_idempotent_on_second_run() {
        let user = r#"
[default_model]
provider = "openrouter"
model = "x"
api_key_env = "OPENROUTER_API_KEY"
"#;
        let first = reconcile_string(user, "v3.14").unwrap();
        assert!(!first.added_keys.is_empty());
        let second = reconcile_string(&first.reconciled, "v3.14").unwrap();
        assert!(second.added_keys.is_empty(), "second run must be a no-op");
    }

    #[test]
    fn reconcile_adds_auto_added_comment_for_sections() {
        let user = r#"
[default_model]
provider = "openrouter"
model = "x"
api_key_env = "OPENROUTER_API_KEY"
"#;
        let r = reconcile_string(user, "v3.14").unwrap();
        assert!(r.reconciled.contains("auto-added by captain v3.14"));
    }

    #[test]
    fn reconcile_file_roundtrips_through_disk() {
        use tempfile::TempDir;
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"
[default_model]
provider = "openrouter"
model = "x"
api_key_env = "OPENROUTER_API_KEY"
"#,
        )
        .unwrap();
        let added = reconcile_file(&path, "v3.14").unwrap();
        assert!(added.contains(&"learning".to_string()));
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("[learning]"));
        // Second run is a no-op: no disk write either, but current
        // impl always writes on any added_keys; after idempotence
        // there are no added_keys so body stays byte-identical.
        let body_before = body.clone();
        let added_again = reconcile_file(&path, "v3.14").unwrap();
        assert!(added_again.is_empty());
        let body_after = std::fs::read_to_string(&path).unwrap();
        assert_eq!(body_before, body_after);
    }

    #[test]
    fn reconcile_errors_out_on_malformed_file() {
        use tempfile::TempDir;
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("broken.toml");
        std::fs::write(&path, "not = valid [toml").unwrap();
        let err = reconcile_file(&path, "v3.14").unwrap_err();
        assert!(matches!(err, ReconcileError::Parse(_)));
        // File left alone.
        let body = std::fs::read_to_string(&path).unwrap();
        assert_eq!(body, "not = valid [toml");
    }
}
