use crate::channel_registry::{ChannelField, ChannelMeta, FieldType};

const EMAIL_FIELDS: &[ChannelField] = &[
    ChannelField {
        key: "username",
        label: "Mailbox Address",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "captain@example.com",
        advanced: false,
    },
    ChannelField {
        key: "password_env",
        label: "Password Secret",
        field_type: FieldType::Secret,
        env_var: Some("EMAIL_PASSWORD"),
        required: true,
        placeholder: "app-password",
        advanced: false,
    },
    ChannelField {
        key: "imap_host",
        label: "IMAP Host",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "imap.example.com",
        advanced: false,
    },
    ChannelField {
        key: "smtp_host",
        label: "SMTP Host",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "smtp.example.com",
        advanced: false,
    },
    ChannelField {
        key: "allowed_senders",
        label: "Allowed Senders",
        field_type: FieldType::List,
        env_var: None,
        required: true,
        placeholder: "boss@example.com, @company.com",
        advanced: false,
    },
    ChannelField {
        key: "default_agent",
        label: "Default Agent",
        field_type: FieldType::Text,
        env_var: None,
        required: false,
        placeholder: "assistant",
        advanced: true,
    },
    ChannelField {
        key: "imap_port",
        label: "IMAP Port",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "993",
        advanced: true,
    },
    ChannelField {
        key: "smtp_port",
        label: "SMTP Port",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "587",
        advanced: true,
    },
    ChannelField {
        key: "poll_interval_secs",
        label: "Poll Interval (sec)",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "30",
        advanced: true,
    },
];

pub(crate) const EMAIL_CHANNEL_META: ChannelMeta = ChannelMeta {
    name: "email",
    display_name: "Email",
    icon: "EM",
    description: "Named IMAP inboxes + SMTP outbound adapters",
    difficulty: "Medium",
    setup_time: "~5 min",
    quick_setup: "Run `captain channel setup email` for each named mailbox",
    fields: EMAIL_FIELDS,
    setup_steps: &[
        "Prefer `captain email connect` for native Gmail OAuth",
        "Create an app password for an IMAP/SMTP fallback mailbox",
        "Set the mailbox address plus IMAP and SMTP hosts",
        "Let Captain store each app password under its generated per-account secret key",
        "Add explicit allowed_senders or \"*\" if open access is intentional",
    ],
    operator_notes: &[
        "Email is deny-by-default: allowed_senders must contain explicit senders, domains, or \"*\".",
        "The API/Web form uses {account: {...}, make_default}; it never returns password values or secret references.",
        "Use an app password; do not store the mailbox password directly in config.toml.",
    ],
    config_template: "[channels.email]\ndefault_account = \"work\"\n\n[[channels.email.accounts]]\nalias = \"work\"\nusername = \"captain@example.com\"\npassword_env = \"CAPTAIN_EMAIL_WORK_PASSWORD\"\nimap_host = \"imap.example.com\"\nsmtp_host = \"smtp.example.com\"\nallowed_senders = []",
};
