use crate::channel_registry::{ChannelField, ChannelMeta, FieldType};

const EMAIL_FIELDS: &[ChannelField] = &[
    ChannelField {
        key: "username",
        label: "Mailbox Address",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "captain@example.com",
        advanced: false,
    },
    ChannelField {
        key: "password_env",
        label: "Password Secret",
        field_type: FieldType::Secret,
        env_var: Some("EMAIL_PASSWORD"),
        required: true,
        placeholder: "app-password",
        advanced: false,
    },
    ChannelField {
        key: "imap_host",
        label: "IMAP Host",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "imap.example.com",
        advanced: false,
    },
    ChannelField {
        key: "smtp_host",
        label: "SMTP Host",
        field_type: FieldType::Text,
        env_var: None,
        required: true,
        placeholder: "smtp.example.com",
        advanced: false,
    },
    ChannelField {
        key: "allowed_senders",
        label: "Allowed Senders",
        field_type: FieldType::List,
        env_var: None,
        required: true,
        placeholder: "boss@example.com, @company.com",
        advanced: false,
    },
    ChannelField {
        key: "default_agent",
        label: "Default Agent",
        field_type: FieldType::Text,
        env_var: None,
        required: false,
        placeholder: "assistant",
        advanced: true,
    },
    ChannelField {
        key: "imap_port",
        label: "IMAP Port",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "993",
        advanced: true,
    },
    ChannelField {
        key: "smtp_port",
        label: "SMTP Port",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "587",
        advanced: true,
    },
    ChannelField {
        key: "poll_interval_secs",
        label: "Poll Interval (sec)",
        field_type: FieldType::Number,
        env_var: None,
        required: false,
        placeholder: "30",
        advanced: true,
    },
];

pub(crate) const EMAIL_CHANNEL_META: ChannelMeta = ChannelMeta {
    name: "email",
    display_name: "Email",
    icon: "EM",
    description: "IMAP inbox + SMTP outbound adapter",
    difficulty: "Medium",
    setup_time: "~5 min",
    quick_setup: "Set IMAP/SMTP hosts, mailbox address, password secret, and allowed senders",
    fields: EMAIL_FIELDS,
    setup_steps: &[
        "Create an app password for the mailbox",
        "Set the mailbox address plus IMAP and SMTP hosts",
        "Store the password in EMAIL_PASSWORD",
        "Add explicit allowed_senders or \"*\" if open access is intentional",
    ],
    operator_notes: &[
        "Email is deny-by-default: allowed_senders must contain explicit senders, domains, or \"*\".",
        "Use an app password; do not store the mailbox password directly in config.toml.",
    ],
    config_template: "[channels.email]\nusername = \"captain@example.com\"\npassword_env = \"EMAIL_PASSWORD\"\nimap_host = \"imap.example.com\"\nsmtp_host = \"smtp.example.com\"\nallowed_senders = []",
};
