//! HTTP/WebSocket API server for the Captain Agent OS daemon.
//!
//! Exposes agent management, status, and chat via JSON REST endpoints.
//! The kernel runs in-process; the CLI connects over HTTP.

pub mod a2a_routes;
pub mod agent_api_audit;
pub mod agent_api_config_status;
pub mod agent_api_egress;
pub mod agent_api_egress_config_routes;
pub mod agent_api_egress_queue;
pub mod agent_api_egress_routes;
pub mod agent_api_idempotency;
pub mod agent_api_ingress_support;
pub mod agent_api_manifest_routes;
pub mod agent_api_routes;
pub mod agent_api_token_routes;
pub mod agent_config_routes;
pub mod agent_control_routes;
pub mod agent_delivery_routes;
pub mod agent_file_routes;
pub mod agent_lifecycle_routes;
pub mod agent_message_routes;
pub mod agent_runtime_config_routes;
pub mod agent_session_view_routes;
pub mod agent_spawn_routes;
pub mod agent_update_routes;
pub mod approval_routes;
pub mod audit_routes;
pub mod binding_routes;
pub mod capspec_routes;
mod channel_audit;
pub mod channel_bridge;
mod channel_config_store;
mod channel_readiness;
mod channel_registry;
mod channel_registry_email;
pub mod channel_routes;
mod channel_runtime_policy;
mod channel_test_delivery;
pub mod clawhub_routes;
pub mod command_routes;
pub mod comms_routes;
pub mod config_routes;
pub mod consciousness_routes;
pub mod cron_routes;
pub mod daemon_commands;
mod daemon_control_drain;
mod daemon_info;
pub mod event_webhooks;
pub mod feedback_routes;
pub mod hand_install_routes;
pub mod hand_instance_routes;
pub mod hand_routes;
pub mod health_routes;
pub mod integration_routes;
pub mod kv_routes;
pub mod learning_routes;
pub mod mcp_routes;
pub mod memory_event_routes;
pub mod memory_migration_routes;
pub mod middleware;
pub mod model_routes;
pub mod model_update_routes;
pub mod openai_compat;
pub mod pairing_routes;
pub mod peer_routes;
mod process_routes;
pub mod profile_routes;
mod project_active_input;
pub mod project_active_routes;
pub mod project_answer_routes;
pub mod project_archive_routes;
pub mod project_ask;
mod project_ask_answering;
mod project_checkpoint_input;
pub mod project_checkpoint_routes;
pub mod project_create_routes;
pub mod project_delete_routes;
pub mod project_detail_routes;
pub mod project_environment_routes;
mod project_environment_view;
pub mod project_github_routes;
mod project_github_view;
mod project_goal_input;
pub mod project_goal_routes;
mod project_goal_runtime;
mod project_launch_error;
mod project_launch_flow;
mod project_launch_input;
mod project_launch_project;
mod project_launch_records;
pub mod project_launch_routes;
mod project_launch_state;
mod project_launch_tasks;
mod project_lifecycle;
pub mod project_lifecycle_routes;
pub mod project_list_routes;
mod project_lookup_input;
mod project_metadata;
mod project_milestone_input;
pub mod project_milestone_routes;
mod project_naming;
pub mod project_resume_routes;
mod project_resume_view;
pub mod project_routes;
mod project_runtime_ask_resume;
mod project_runtime_asks;
mod project_runtime_checkpoints;
mod project_runtime_defaults;
mod project_runtime_events;
mod project_runtime_mutation;
mod project_runtime_orchestrator;
pub mod project_runtime_pause_routes;
mod project_runtime_prompt_context;
mod project_runtime_response;
mod project_runtime_resume;
pub mod project_runtime_resume_routes;
mod project_runtime_route_support;
pub mod project_runtime_routes;
mod project_runtime_runner;
mod project_runtime_start;
pub mod project_runtime_start_routes;
mod project_runtime_state;
mod project_runtime_status;
mod project_runtime_status_safe;
mod project_runtime_stream_ask;
mod project_runtime_stream_events;
pub mod project_runtime_takeover_routes;
mod project_runtime_tool_status;
mod project_runtime_view;
mod project_runtime_view_window;
mod project_runtime_worker_cleanup;
mod project_runtime_worker_decision;
mod project_runtime_worker_failure;
mod project_runtime_worker_manifest;
mod project_runtime_worker_model;
mod project_runtime_worker_phase_finish;
mod project_runtime_worker_phase_start;
mod project_runtime_worker_recovery;
mod project_runtime_worker_result;
mod project_runtime_worker_spawn;
mod project_runtime_worker_summary;
mod project_runtime_worker_support;
mod project_runtime_worker_tools;
mod project_runtime_worker_turn;
mod project_runtime_workers;
pub mod project_slash;
mod project_storage_error;
mod project_task_input;
pub mod project_task_routes;
mod project_tool_request_decision;
pub mod project_tool_request_routes;
mod project_tool_request_runtime;
mod project_tool_request_view;
mod project_update_input;
pub mod project_update_routes;
mod project_workspace;
pub mod provider_oauth_routes;
pub mod provider_quota_status;
pub mod provider_routes;
pub mod rate_limiter;
pub mod realtime_call;
mod restart_dedupe;
pub mod routes;
pub mod schedule_routes;
pub mod secret_env;
pub mod security_routes;
pub mod server;
mod server_a2a_routes;
mod server_agent_routes;
mod server_automation_routes;
mod server_capability_routes;
mod server_channel_routes;
mod server_control_routes;
mod server_coordination_routes;
mod server_governance_routes;
mod server_hand_routes;
mod server_integration_routes;
mod server_learning_engine_routes;
mod server_learning_routes;
mod server_maintenance_routes;
mod server_memory_graph_routes;
mod server_observability_routes;
mod server_project_routes;
mod server_protocol_routes;
mod server_runtime_adapters;
mod server_session_io_routes;
mod server_session_management_routes;
mod server_settings_routes;
mod server_skill_routes;
mod server_web_routes;
pub mod session_auth;
pub mod session_routes;
mod shutdown_guard;
pub mod skill_routes;
pub mod ssrf_pin;
pub mod state;
mod status_agent_api;
mod status_automation;
mod status_consciousness;
pub mod status_disk;
mod status_payload;
mod status_processes;
pub mod status_routes;
pub mod status_runtime_health;
pub mod stream_chunker;
pub mod stream_dedup;
mod stream_metrics;
pub mod streaming_channels;
pub mod system_routes;
pub mod telegram_topic_routes;
pub mod template_routes;
pub mod timeline;
pub mod tool_routes;
pub mod trigger_routes;
pub mod types;
pub mod upload_routes;
pub mod usage_budget_routes;
pub mod voice_routes;
pub mod web_auth_routes;
pub mod webchat;
pub mod webhook_routes;
pub mod whatsapp_routes;
pub mod workflow_routes;
pub mod ws;
pub mod ws_terminal;

/// Convenience re-export for publishing chat events from WS and channel bridge.
pub(crate) async fn chat_broadcast_publish(
    bus: &captain_kernel::event_bus::EventBus,
    agent_id: captain_types::agent::AgentId,
    event: captain_types::event::ChatStreamEvent,
) {
    captain_kernel::chat_broadcast::publish_chat_event(bus, agent_id, event).await;
}
